# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 京喜工厂

on:
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *'
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
          npm install got download tough-cookie
      - name: ' 运行 【京喜工厂】'
        if: env.JD_COOKIE
        run: |
          node Scripts/jx_factory.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
